#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="/scratch/work/sethih1/RNA-prediction"
SOLUTION_ROOT="${REPO_ROOT}/sin-Stanford-RNA-3D-Folding-2/kaggle-new-solution"
SLURM_SCRIPT="${SOLUTION_ROOT}/slurm/run_official_protenix_train_h200.sh"

VENV_ACTIVATE="${VENV_ACTIVATE:-/scratch/phys/sin/rna-dataset/venv/px-kaggle/bin/activate}"
PROTENIX_REPO_DIR="${PROTENIX_REPO_DIR:-${REPO_ROOT}/sin-Stanford-RNA-3D-Folding-2/external/Protenix-v1-official}"
CACHE_ROOT="${CACHE_ROOT:-/scratch/phys/sin/rna-dataset/preprocessed_data}"
CCD_ROOT="${CCD_ROOT:-/scratch/phys/sin/rna-dataset/protenix_ccd_cache}"
RUN_BASE_DIR="${RUN_BASE_DIR:-/scratch/phys/sin/rna-dataset/protenix_runs}"
RUN_NAME="${RUN_NAME:-kaggle_new_solution_ft_$(date +%Y%m%d_%H%M%S)}"
CHECKPOINT_SAVE_DIR="${CHECKPOINT_SAVE_DIR:-/scratch/phys/sin/rna-dataset/models}"
CHECKPOINT_PATH="${CHECKPOINT_PATH:-/scratch/phys/sin/rna-dataset/protenix_checkpoint/protenix_base_20250630_v1.0.0.pt}"
EMA_CHECKPOINT_PATH="${EMA_CHECKPOINT_PATH:-}"
USE_MSA="${USE_MSA:-true}"
USE_WANDB="${USE_WANDB:-true}"
WANDB_PROJECT="${WANDB_PROJECT:-protenix-v1-rna}"
WANDB_ID="${WANDB_ID:-}"
WANDB_MODE="${WANDB_MODE:-online}"
MAX_STEPS="${MAX_STEPS:-5000}"
TRAIN_CROP_SIZE="${TRAIN_CROP_SIZE:-416}"
EVAL_INTERVAL="${EVAL_INTERVAL:-1000}"
CHECKPOINT_INTERVAL="${CHECKPOINT_INTERVAL:-100}"
LOG_INTERVAL="${LOG_INTERVAL:-1}"
LR="${LR:-5e-5}"
SEED="${SEED:-42}"
EMA_DECAY="${EMA_DECAY:-0.995}"
PROTENIX_DISABLE_EVAL="${PROTENIX_DISABLE_EVAL:-0}"
PROTENIX_ENABLE_VALIDATION_EVAL="${PROTENIX_ENABLE_VALIDATION_EVAL:-1}"
LAYERNORM_TYPE="${LAYERNORM_TYPE:-openfold}"
NUM_WORKERS="${NUM_WORKERS:-0}"
TRAIN_BATCH_SIZE="${TRAIN_BATCH_SIZE:-32}"
DIFFUSION_BATCH_SIZE="${DIFFUSION_BATCH_SIZE:-8}"

SBATCH_EXPORTS=(
  "ALL"
  "VENV_ACTIVATE=${VENV_ACTIVATE}"
  "PROTENIX_REPO_DIR=${PROTENIX_REPO_DIR}"
  "CACHE_ROOT=${CACHE_ROOT}"
  "CCD_ROOT=${CCD_ROOT}"
  "RUN_BASE_DIR=${RUN_BASE_DIR}"
  "RUN_NAME=${RUN_NAME}"
  "CHECKPOINT_SAVE_DIR=${CHECKPOINT_SAVE_DIR}"
  "CHECKPOINT_PATH=${CHECKPOINT_PATH}"
  "USE_MSA=${USE_MSA}"
  "USE_WANDB=${USE_WANDB}"
  "WANDB_PROJECT=${WANDB_PROJECT}"
  "WANDB_MODE=${WANDB_MODE}"
  "MAX_STEPS=${MAX_STEPS}"
  "TRAIN_CROP_SIZE=${TRAIN_CROP_SIZE}"
  "EVAL_INTERVAL=${EVAL_INTERVAL}"
  "CHECKPOINT_INTERVAL=${CHECKPOINT_INTERVAL}"
  "LOG_INTERVAL=${LOG_INTERVAL}"
  "LR=${LR}"
  "SEED=${SEED}"
  "EMA_DECAY=${EMA_DECAY}"
  "PROTENIX_DISABLE_EVAL=${PROTENIX_DISABLE_EVAL}"
  "PROTENIX_ENABLE_VALIDATION_EVAL=${PROTENIX_ENABLE_VALIDATION_EVAL}"
  "LAYERNORM_TYPE=${LAYERNORM_TYPE}"
  "NUM_WORKERS=${NUM_WORKERS}"
  "TRAIN_BATCH_SIZE=${TRAIN_BATCH_SIZE}"
  "DIFFUSION_BATCH_SIZE=${DIFFUSION_BATCH_SIZE}"
)

if [[ -n "${EMA_CHECKPOINT_PATH}" ]]; then
  SBATCH_EXPORTS+=("EMA_CHECKPOINT_PATH=${EMA_CHECKPOINT_PATH}")
fi

if [[ -n "${WANDB_ID}" ]]; then
  SBATCH_EXPORTS+=("WANDB_ID=${WANDB_ID}")
fi

if [[ -n "${WANDB_API_KEY:-}" ]]; then
  SBATCH_EXPORTS+=("WANDB_API_KEY=${WANDB_API_KEY}")
fi

EXPORT_STRING="$(IFS=,; printf '%s' "${SBATCH_EXPORTS[*]}")"

echo "Submitting ${SLURM_SCRIPT}"
echo "RUN_NAME=${RUN_NAME}"
echo "CHECKPOINT_SAVE_DIR=${CHECKPOINT_SAVE_DIR:-<default under run dir>}"
echo "USE_WANDB=${USE_WANDB}"
echo "WANDB_PROJECT=${WANDB_PROJECT}"
echo "WANDB_MODE=${WANDB_MODE}"

sbatch --export="${EXPORT_STRING}" "$@" "${SLURM_SCRIPT}"
