_allow_dotted_keys:
    value: false
_convert_dict:
    value: true
_fields:
    value:
        adam: |
            beta1: 0.9
            beta2: 0.95
            lr: 0.0001
            use_adamw: false
            weight_decay: 1.0e-08
        af3_lr_scheduler: |
            decay_every_n_steps: 50000
            decay_factor: 0.95
            lr: 0.0001
            warmup_steps: 50
        atom_permutation: |
            global_align_wo_symmetric_atom: false
            permute_by_pocket: true
            test:
              diffusion_sample: true
            train:
              diffusion_sample: false
              mini_rollout: true
        base_dir: /scratch/work/sethih1/RNA-prediction/sin-Stanford-RNA-3D-Folding-2/kaggle-part-2-solution/references/protenix_runs
        blocks_per_ckpt: 1
        c_atom: 128
        c_atompair: 16
        c_s: 384
        c_s_inputs: 449
        c_token: 384
        c_z: 128
        chain_permutation: |
            configs:
              accept_it_as_it_is: false
              enumerate_all_anchor_pairs: false
              find_gt_anchor_first: false
              selection_metric: aligned_rmsd
              use_center_rmsd: false
            permute_by_pocket: true
            test:
              diffusion_sample: true
            train:
              diffusion_sample: false
              mini_rollout: true
        checkpoint_interval: 100
        data: |
            ccd_components_file: /scratch/work/sethih1/RNA-prediction/sin-Stanford-RNA-3D-Folding-2/kaggle-part-2-solution/references/protenix_ccd_cache/components.v20240608.cif
            ccd_components_rdkit_mol_file: /scratch/work/sethih1/RNA-prediction/sin-Stanford-RNA-3D-Folding-2/kaggle-part-2-solution/references/protenix_ccd_cache/components.v20240608.cif.rdkit_mol.pkl
            epoch_size: 10000
            msa:
              enable: true
              enable_rna_msa: false
              max_size:
                test: 16384
                train: 16384
              merge_method: dense_max
              min_size:
                test: 2048
                train: 1
              prot:
                indexing_method: sequence
                non_pairing_db: mmseqs_other
                pairing_db: uniref100
                pdb_mmseqs_dir: /home/lhw/work/rna2025/release_data/mmcif_msa
                seq_to_pdb_idx_path: /home/lhw/work/rna2025/release_data/seq_to_pdb_index.json
              rna:
                indexing_method: sequence
                rna_msa_dir: ''
                seq_to_pdb_idx_path: ''
              sample_cutoff:
                test: 2048
                train: 2048
              strategy: random
            num_dl_workers: 16
            posebusters_0925:
              base_info:
                bioassembly_dict_dir: /home/lhw/work/rna2025/release_data/posebusters_bioassembly
                find_all_pockets: false
                find_pocket: true
                indices_fpath: /home/lhw/work/rna2025/release_data/indices/posebusters_indices_mainchain_interface.csv
                max_n_token: -1
                mmcif_dir: /home/lhw/work/rna2025/release_data/posebusters_mmcif
                pdb_list: ''
              cropping_configs:
                crop_size: -1
                method_weights:
                - 0.0
                - 0.0
                - 1.0
              lig_atom_rename: false
              sampler_configs:
                sampler_type: uniform
              shuffle_mols: false
              shuffle_sym_ids: false
            recentPDB_1536_sample384_0925:
              base_info:
                bioassembly_dict_dir: /home/lhw/work/rna2025/release_data/recentPDB_bioassembly
                find_eval_chain_interface: true
                group_by_pdb_id: true
                indices_fpath: /home/lhw/work/rna2025/release_data/indices/recentPDB_low_homology_maxtoken1536.csv
                max_n_token: -1
                mmcif_dir: /home/lhw/work/rna2025/release_data/mmcif
                pdb_list: /home/lhw/work/rna2025/release_data/indices/recentPDB_low_homology_maxtoken1024_sample384_pdb_id.txt
                sort_by_n_token: false
              cropping_configs:
                crop_size: -1
                method_weights:
                - 0.0
                - 0.0
                - 1.0
              lig_atom_rename: false
              sampler_configs:
                sampler_type: uniform
              shuffle_mols: false
              shuffle_sym_ids: false
            template:
              enable: false
            test_ref_pos_augment: true
            test_sets:
            - recentPDB_1536_sample384_0925
            train_ref_pos_augment: true
            train_sampler:
              sampler_type: weighted
              train_sample_weights:
              - 1.0
            train_sets:
            - weightedPDB_before2109_wopb_nometalc_0925
            weightedPDB_before2109_wopb_nometalc_0925:
              base_info:
                bioassembly_dict_dir: /home/lhw/work/rna2025/release_data/mmcif_bioassembly
                exclusion:
                  mol_1_type:
                  - ions
                  mol_2_type:
                  - ions
                indices_fpath: /home/lhw/work/rna2025/release_data/indices/weightedPDB_indices_before_2021-09-30_wo_posebusters_resolution_below_9.csv.gz
                max_n_token: -1
                mmcif_dir: /home/lhw/work/rna2025/release_data/mmcif
                pdb_list: ''
                random_sample_if_failed: true
                use_reference_chains_only: false
              cropping_configs:
                crop_size: 416
                method_weights:
                - 0.2
                - 0.4
                - 0.4
              lig_atom_rename: false
              limits: -1
              sample_weight: 0.5
              sampler_configs:
                alpha_dict:
                  ligand: 1
                  nuc: 3
                  prot: 3
                beta_dict:
                  chain: 0.5
                  interface: 1
                force_recompute_weight: true
                sampler_type: weighted
              shuffle_mols: false
              shuffle_sym_ids: false
        decay_every_n_steps: 50000
        deterministic: false
        diffusion_batch_size: 8
        diffusion_chunk_size: 4
        dtype: bf16
        ema_decay: 0.995
        ema_mutable_param_keywords:
            - ""
        eval_ema_only: false
        eval_first: false
        eval_interval: 1000
        eval_only: false
        find_unused_parameters: false
        grad_clip_norm: 10
        infer_setting: |
            chunk_size: 64
            lddt_metrics_chunk_size: 1
            lddt_metrics_sparse_enable: true
            sample_diffusion_chunk_size: 1
        inference_noise_scheduler: |
            rho: 7
            s_max: 160.0
            s_min: 0.0004
            sigma_data: 16.0
        iters_to_accumulate: 1
        load_checkpoint_path: /scratch/work/sethih1/RNA-prediction/sin-Stanford-RNA-3D-Folding-2/kaggle-part-2-solution/references/protenix_checkpoint/model_v0.2.0.pt
        load_ema_checkpoint_path: ""
        load_params_only: true
        load_strict: true
        log_interval: 1
        loss: |
            diffusion:
              bond:
                eps: 1.0e-06
              mse:
                eps: 1.0e-06
                weight_dna: 5.0
                weight_ligand: 10.0
                weight_mse: 0.3333333333333333
                weight_rna: 5.0
              smooth_lddt:
                eps: 1.0e-06
            diffusion_bond_chunk_size: 1
            diffusion_chunk_size_outer: -1
            diffusion_lddt_chunk_size: 1
            diffusion_lddt_loss_dense: true
            diffusion_sparse_loss_enable: true
            distogram:
              eps: 1.0e-06
              max_bin: 21.6875
              min_bin: 2.3125
              no_bins: 64
            pae:
              eps: 1.0e-06
              max_bin: 32
              min_bin: 0
              no_bins: 64
            pde:
              eps: 1.0e-06
              max_bin: 32
              min_bin: 0
              no_bins: 64
            plddt:
              eps: 1.0e-06
              max_bin: 1.0
              min_bin: 0
              no_bins: 50
              normalize: true
            resolution:
              max: 4.0
              min: 0.1
            resolved:
              eps: 1.0e-06
            weight:
              alpha_bond: 0.0
              alpha_confidence: 0.0001
              alpha_diffusion: 4.0
              alpha_distogram: 0.03
              alpha_except_pae: 1.0
              alpha_pae: 0.0
              smooth_lddt: 1.0
        loss_metrics_sparse_enable: true
        lr: 0.0001
        lr_scheduler: af3
        max_atoms_per_token: 24
        max_steps: 200
        metrics: |
            chain_ranker_keys:
            - chain_ptm
            - chain_plddt
            clash:
              af3_clash_threshold: 1.1
              vdw_clash_threshold: 0.75
            complex_ranker_keys:
            - plddt
            - gpde
            - ranking_score
            interface_ranker_keys:
            - chain_pair_iptm
            - chain_pair_iptm_global
            - chain_pair_plddt
            lddt:
              eps: 1.0e-06
        min_lr_ratio: 0.1
        model: |
            N_cycle: 4
            N_model_seed: 1
            confidence_head:
              blocks_per_ckpt: 1
              c_s: 384
              c_s_inputs: 449
              c_z: 128
              distance_bin_end: 52.0
              distance_bin_start: 3.25
              distance_bin_step: 1.25
              max_atoms_per_token: 24
              n_blocks: 4
              pairformer_dropout: 0.0
              stop_gradient: true
            diffusion_module:
              atom_decoder:
                n_blocks: 3
                n_heads: 4
              atom_encoder:
                n_blocks: 3
                n_heads: 4
              blocks_per_ckpt: 1
              c_atom: 128
              c_atompair: 16
              c_s: 384
              c_s_inputs: 449
              c_token: 768
              c_z: 128
              initialization:
                glorot_init_self_attention: false
                he_normal_init_atom_encoder_output: false
                he_normal_init_atom_encoder_small_mlp: false
                zero_init_adaln: true
                zero_init_atom_decoder_linear: false
                zero_init_atom_encoder_residual_linear: false
                zero_init_condition_transition: false
                zero_init_dit_output: true
                zero_init_residual_condition_transition: false
              sigma_data: 16.0
              transformer:
                n_blocks: 24
                n_heads: 16
              use_fine_grained_checkpoint: true
            distogram_head:
              c_z: 128
              no_bins: 64
            input_embedder:
              c_atom: 128
              c_atompair: 16
              c_token: 384
            msa_module:
              blocks_per_ckpt: 1
              c_m: 64
              c_s_inputs: 449
              c_z: 128
              msa_dropout: 0.15
              n_blocks: 4
              pair_dropout: 0.25
            pairformer:
              blocks_per_ckpt: 1
              c_s: 384
              c_z: 128
              dropout: 0.25
              n_blocks: 48
              n_heads: 16
            relative_position_encoding:
              c_z: 128
              r_max: 32
              s_max: 2
            template_embedder:
              blocks_per_ckpt: 1
              c: 64
              c_z: 128
              dropout: 0.25
              n_blocks: 0
        n_blocks: 48
        no_bins: 64
        project: protenix-kaggle-native
        run_name: kaggle_native_ft
        sample_diffusion: |
            N_sample: 5
            N_sample_mini_rollout: 1
            N_step: 20
            N_step_mini_rollout: 20
            gamma0: 0.8
            gamma_min: 1.0
            noise_scale_lambda: 1.003
            step_scale_eta: 1.5
        seed: 42
        sigma_data: 16
        skip_amp: |
            confidence_head: true
            loss: true
            sample_diffusion: true
            sample_diffusion_training: true
        skip_load_optimizer: false
        skip_load_scheduler: false
        skip_load_step: false
        test_lig_atom_rename: false
        test_max_n_token: -1
        test_shuffle_mols: false
        test_shuffle_sym_ids: false
        train_confidence_only: false
        train_crop_size: 416
        train_lig_atom_rename: false
        train_noise_sampler: |
            p_mean: -1.2
            p_std: 1.5
            sigma_data: 16.0
        train_shuffle_mols: false
        train_shuffle_sym_ids: false
        use_deepspeed_evo_attention: false
        use_flash: false
        use_lma: false
        use_memory_efficient_kernel: false
        use_msa: false
        use_wandb: true
        use_xformer: false
        wandb_id: ""
        warmup_steps: 50
_locked:
    value: false
_sort_keys:
    value: true
_type_safe:
    value: true
_wandb:
    value:
        cli_version: 0.25.0
        e:
            trr8au0ucsghvj66onq2rhpj5odojaiy:
                args:
                    - --run_name
                    - kaggle_native_ft
                    - --seed
                    - "42"
                    - --base_dir
                    - /scratch/work/sethih1/RNA-prediction/sin-Stanford-RNA-3D-Folding-2/kaggle-part-2-solution/references/protenix_runs
                    - --dtype
                    - bf16
                    - --use_msa
                    - "false"
                    - --project
                    - protenix-kaggle-native
                    - --use_wandb
                    - "true"
                    - --diffusion_batch_size
                    - "8"
                    - --eval_interval
                    - "1000"
                    - --log_interval
                    - "1"
                    - --checkpoint_interval
                    - "100"
                    - --ema_decay
                    - "0.995"
                    - --train_crop_size
                    - "416"
                    - --max_steps
                    - "200"
                    - --warmup_steps
                    - "50"
                    - --lr
                    - "1e-4"
                    - --sample_diffusion.N_step
                    - "20"
                    - --load_checkpoint_path
                    - /scratch/work/sethih1/RNA-prediction/sin-Stanford-RNA-3D-Folding-2/kaggle-part-2-solution/references/protenix_checkpoint/model_v0.2.0.pt
                codePath: kaggle-part-2-solution/code/launch_kaggle_native_train.py
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1080234577920"
                        used: "4566331392"
                email: sethih10@gmail.com
                executable: /scratch/phys/sin/rna-dataset/protenix-kaggle-lite-venv/bin/python
                git:
                    commit: 70b0b5074061bbdbec74196fb363b59eb8cf801a
                    remote: https://github.com/mundaron/sin-Stanford-RNA-3D-Folding-2.git
                gpu: NVIDIA H200
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200
                      uuid: GPU-21740514-a3c9-d708-9318-e714bde48ce8
                host: gpu50.int.triton.aalto.fi
                memory:
                    total: "2163998212096"
                os: Linux-5.14.0-570.77.1.el9_6.x86_64-x86_64-with-glibc2.34
                program: /scratch/work/sethih1/RNA-prediction/sin-Stanford-RNA-3D-Folding-2/kaggle-part-2-solution/code/launch_kaggle_native_train.py
                python: CPython 3.12.2
                root: /scratch/work/sethih1/RNA-prediction/sin-Stanford-RNA-3D-Folding-2/kaggle-part-2-solution/slurm
                slurm:
                    cluster_name: triton
                    conf: /var/spool/slurmd/conf-cache/slurm.conf
                    cpus_on_node: "16"
                    cpus_per_task: "16"
                    export_env: ALL,VENV_ACTIVATE=/scratch/phys/sin/rna-dataset/protenix-kaggle-lite-venv/bin/activate,USE_WANDB=true,WANDB_PROJECT=protenix-kaggle-native,WANDB_MODE=online
                    get_user_env: "1"
                    gpus: "1"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: aalto_users
                    job_cpus_per_node: "16"
                    job_end_time: "1773861597"
                    job_gid: "3155757"
                    job_gpus: "4"
                    job_id: "16747841"
                    job_name: ptx-native-train
                    job_nodelist: gpu50
                    job_num_nodes: "1"
                    job_partition: gpu-h200-141g-short
                    job_qos: normal
                    job_start_time: "1773832797"
                    job_uid: "3155757"
                    job_user: sethih1
                    jobid: "16747841"
                    localid: "0"
                    mem_per_node: "122880"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: gpu50
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    submit_dir: /scratch/work/sethih1/RNA-prediction/sin-Stanford-RNA-3D-Folding-2/kaggle-part-2-solution/slurm
                    submit_host: login4.triton.aalto.fi
                    task_pid: "3963431"
                    tasks_per_node: "1"
                    topology_addr: s0-0.s1-18.gpu50
                    topology_addr_pattern: switch.switch.node
                    tres_per_task: cpu=16
                startedAt: "2026-03-18T11:20:05.292690Z"
                writerId: trr8au0ucsghvj66onq2rhpj5odojaiy
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 5
                - 53
                - 105
            "2":
                - 1
                - 5
                - 53
                - 105
            "3":
                - 13
                - 16
                - 61
            "4": 3.12.2
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
